/* All analytics are opt-in device-local prototype observations. No remote collection. */
const ConceptLab=(()=>{
 const app=document.body.dataset.concept;
 const names={quest:'Quest',oshii:'惜しい','epos-gold':'EPOS GOLD'};
 const key='marui-concept-lab:v2';
 let enabled=false, storageWarning=false;
 const sid=globalThis.crypto?.randomUUID?.()||String(Date.now())+'-'+Math.random().toString(36).slice(2);
 let records=[];
 try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(data))records=data.filter(r=>r&&typeof r.app==='string'&&typeof r.event==='string'&&typeof r.session==='string'&&typeof r.at==='string'&&r.meta&&typeof r.meta==='object').slice(-5000)}catch{}
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function save(){try{localStorage.setItem(key,JSON.stringify(records))}catch{storageWarning=true}}
 function track(event,meta={}){if(!enabled)return;records.push({app,event,session:sid,at:new Date().toISOString(),meta,source:'prototype_device_local'});records=records.slice(-5000);save()}
 function recordsForApp(){return records.filter(r=>r.app===app)}
 function count(event){return new Set(recordsForApp().filter(r=>r.event===event).map(r=>r.session)).size}
 function metric(label,event){return `<div class="lab-kpi"><span>${label}</span><b>${count(event)}</b></div>`}
 function bars(defs){const max=Math.max(1,...defs.map(d=>count(d[1])));return defs.map(([label,event])=>`<div class="lab-bar"><span>${label}</span><div class="lab-track"><i style="width:${100*count(event)/max}%"></i></div><b>${count(event)}</b></div>`).join('')}
 const defs={quest:[['案内を開始','journey_start'],['目的フロア到着','destination_floor'],['推薦を表示','recommendations'],['寄り道経路表示','detour_route'],['寄り道フロア到着','detour_floor']],oshii:[['商品を保存','saved'],['近接通知を再現','notice_sent'],['通知を開く','notice_open'],['現物を確認','try_result'],['購入を体験','purchase']], 'epos-gold':[['ポイント交換画面','conversion_open'],['金への交換を体験','converted'],['現物交換画面','reward_open'],['費用を確認','fee_shown'],['現物交換を体験','redeemed']]};
 function pairedRate(start,end){const group=new Set(recordsForApp().filter(r=>r.event===start).map(r=>r.session));const done=new Set(recordsForApp().filter(r=>r.event===end&&group.has(r.session)).map(r=>r.session));return group.size?`${Math.round(done.size/group.size*100)}% (${done.size}/${group.size})`:'未計測'}
 function toolbar(){const el=document.createElement('aside');el.className='lab-toolbar';el.innerHTML=`<a href="./">惜しい</a><label><input id="labConsent" type="checkbox">操作をこの端末に記録する</label><button class="btn secondary" onclick="view('validation')">検証を見る</button><small>外部送信なし・位置座標や映像は記録しません</small>`;document.querySelector('header').after(el);el.querySelector('input').addEventListener('change',e=>{enabled=e.target.checked;if(enabled){track('session_start',{view:state.view});if(app==='quest')track('journey_start',{origin:state.origin||'アプリから直接',destination:state.destination});else if(app==='epos-gold'&&state.view==='reward')track('reward_open');}if(state.view==='validation')render()})}
 function definition(){if(app==='quest')return `寄り道先フロア到達 ÷ 推薦を表示したセッション。フロア到達は手動の体験記録で、実来店を証明しません。アプリを閉じた状態は「画面非表示」として記録し、施設からの退出は不明として扱います。`;if(app==='oshii')return `現物確認後の購入セッション ÷ 現物確認セッション。ここでの確認と注文はすべてデモ操作です。本番では対象者を比較群に分け、通知以外の条件をそろえて増分購入・粗利・返品を測ります。`;return `費用提示後の交換意向と、実際の交換体験を分けて集計します。デモの交換数からカード利用の増加や継続率は判断できません。`}
 function resultsTable(){const feedback=recordsForApp().filter(r=>r.event==='feedback');const latest=new Map();feedback.forEach(r=>latest.set(r.session,r));const rows=[...latest.values()];return rows.length?`<div class="lab-table"><table><caption>各セッションの最新回答 ${rows.length}件</caption><thead><tr><th>利用場面</th><th>利用意向</th><th>理由</th><th>使いやすさ</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.meta.scenario)}</td><td>${esc(r.meta.intent)}</td><td>${esc(r.meta.reason)}</td><td>${esc(r.meta.ease)} / 5</td></tr>`).join('')}</tbody></table></div>`:'<p class="lab-empty">まだ回答はありません。下のフォームから体験後の感想を残せます。</p>'}
 function calculator(){if(app==='quest')return `<h2>記録の確かさを確認する</h2><p>QR起点・目的地・推薦一覧・比較したイベント・経路表示を記録。フロア到達は手動ボタンで確かめます。</p><div class="lab-result"><b>実来店・施設退出：未確認</b><p>GPS単独では屋内のフロアを判定できません。実証時にはフロアQRや現地観察を照合します。</p></div><p class="lab-sub">居住地からの吸引距離は別途同意とデータが必要です。端末の現在地だけでは算出しません。</p>`;
 if(app==='oshii')return `<h2>増分利益を試算する</h2><p class="lab-sub">すべて説明用の仮定です。実績・予測ではありません。</p><div class="lab-form"><label>対象者数<input id="calcN" type="number" min="1" max="10000000" value="1000" oninput="ConceptLab.calculate()"></label><div class="lab-grid"><label>通知なし購入率（%）<input id="calcBase" type="number" min="0" max="100" step="0.1" value="3" oninput="ConceptLab.calculate()"></label><label>通知あり購入率（%）<input id="calcLift" type="number" min="0" max="100" step="0.1" value="5" oninput="ConceptLab.calculate()"></label></div><div class="lab-grid"><label>客単価（円）<input id="calcPrice" type="number" min="0" max="10000000" value="8000" oninput="ConceptLab.calculate()"></label><label>粗利率（%）<input id="calcMargin" type="number" min="0" max="100" value="40" oninput="ConceptLab.calculate()"></label></div><label>対応・運用費（円）<input id="calcCost" type="number" min="0" max="100000000" value="20000" oninput="ConceptLab.calculate()"></label><label>通常配布との差分の割引負担総額（円）<input id="calcDiscount" type="number" min="0" max="100000000" value="0" oninput="ConceptLab.calculate()"></label></div><div id="calcResult" class="lab-result" aria-live="polite"></div><p class="lab-sub">式：対象者数 × 購入率差 × 客単価 × 粗利率 − 対応運用費 − 追加割引負担。既存配布との差分だけを割引負担に入力します。返品や固定費はこの簡易試算に含みません。</p>`;
 return `<h2>目標までの期間と費用を試す</h2><p class="lab-sub">価格は説明用の仮定。実際の金相場・交換条件ではありません。</p><div class="lab-form"><label>説明用の金価格（円 / g）<input id="calcGold" type="number" min="1" max="10000000" value="20000" oninput="ConceptLab.calculate()"></label><label>毎月交換するポイント（pt）<input id="calcMonthly" type="number" min="1" max="10000000" value="1000" oninput="ConceptLab.calculate()"></label><label>目標重量（g）<input id="calcGoal" type="number" min="0.001" max="100" step="0.1" value="1" oninput="ConceptLab.calculate()"></label><label>加工・配送費の説明例（円）<input id="calcFee" type="number" min="0" max="1000000" value="3000" oninput="ConceptLab.calculate()"></label></div><div id="calcResult" class="lab-result" aria-live="polite"></div><p class="lab-sub">1pt＝1円と仮定。必要月数は現在のデモ残高から算出します。費用変更は本体の交換条件には反映しません。</p><button class="primary" onclick="ConceptLab.feeOpinion('この費用でも交換したい')">この費用でも交換したい</button> <button onclick="ConceptLab.feeOpinion('この費用なら見送る')">この費用なら見送る</button><p id="feeStatus" class="lab-status" role="status"></p>`}
 function feedbackForm(){const scenarios=app==='quest'?['目当ての店の用事後に時間が余った','館内で目的地が分からない','使う場面が思いつかない']:app==='oshii'?['サイズが不安で購入を保留した','質感や色を確かめたかった','使う場面が思いつかない']:['好きな作品のコインを集めたい','ポイントの使い道を探していた','使う場面が思いつかない'];return `<h2>体験後の感想を残す</h2><p class="lab-sub">操作記録を有効にすると、回答をこの端末に保存できます。個人情報は入力しません。</p><form class="lab-form" onsubmit="event.preventDefault();ConceptLab.feedback(this)"><label>当てはまる利用場面<select name="scenario">${scenarios.map(s=>`<option>${s}</option>`).join('')}</select></label><label>この場面で使いたい？<select name="intent"><option>使いたい</option><option>条件が合えば使いたい</option><option>使わない</option></select></label><label>判断した理由<select name="reason"><option>今の困りごとを解消できそう</option><option>操作が面倒</option><option>情報の正確さが気になる</option><option>費用に見合わない</option><option>今の方法で足りる</option></select></label><label>使いやすさ（1が低い、5が高い）<select name="ease">${[1,2,3,4,5].map(n=>`<option ${n===3?'selected':''}>${n}</option>`).join('')}</select></label><button class="primary" type="submit">回答を保存</button><p id="feedbackStatus" class="lab-status" role="status"></p></form>`}
 function page(){const rate=app==='quest'?pairedRate('recommendations','detour_floor'):app==='oshii'?pairedRate('try_result','purchase'):pairedRate('reward_open','redeemed');return `<section class="lab-page" style="--lab:${app==='quest'?'#176a78':app==='oshii'?'#b42361':'#836120'}"><p class="lab-sub">${names[app]} / 体験テスト</p><h1>利用場面と操作を確かめる</h1><p>この端末で同意して記録したデモ操作を集計します。実際の来店・注文・金取引の実績ではありません。</p><div class="lab-kpis">${metric('記録セッション','session_start')}${metric('最後の操作まで体験',app==='quest'?'detour_floor':app==='oshii'?'purchase':'redeemed')}<div class="lab-kpi"><span>体験上の到達率</span><b style="font-size:22px">${rate}</b></div></div><div class="lab-grid"><section class="lab-card"><h2>操作の進み方</h2><p class="lab-sub">各操作を行ったセッション数。1セッションは、このページを開いている間です。</p>${bars(defs[app])}<p class="lab-sub">${definition()}</p><div class="lab-actions"><button onclick="ConceptLab.download()">記録CSVを保存</button><button onclick="ConceptLab.clear()">この企画の記録を削除</button><button onclick="view('home')">アプリを体験</button></div>${storageWarning?'<p class="lab-sub">端末への保存に失敗しました。現在の画面内の記録をCSVで保存してください。</p>':''}</section><section class="lab-card">${calculator()}</section></div><section class="lab-card">${feedbackForm()}</section><section class="lab-card"><h2>回答の一覧</h2>${resultsTable()}</section><section class="lab-card"><h2>記録の範囲</h2><p>操作記録は上部のチェックを入れた時点から始まります。最大5,000件をこのブラウザに保存します。別端末の回答は自動で集まりません。CSVを集めて分析するための試作です。</p><p class="lab-sub">位置座標・映像・名前・会員番号は記録しません。画面非表示は観測できますが、アプリ終了や館からの退出は確定できません。実サービス化には集約先、会員・在庫・決済などの連携が必要です。</p></section></section>`}
 function num(id){const el=document.getElementById(id);if(!el||el.value.trim()==='')return null;const n=Number(el.value);return Number.isFinite(n)&&el.checkValidity()?n:null}
 function calculate(){const el=document.getElementById('calcResult');if(!el)return;if(app==='oshii'){const v=['calcN','calcBase','calcLift','calcPrice','calcMargin','calcCost','calcDiscount'].map(num);if(v.some(n=>n===null)){el.textContent='範囲内の数値を入力してください。';return}const [n,b,l,p,m,c,d]=v,orders=n*(l-b)/100,profit=orders*p*m/100-c-d;el.innerHTML=`<span>説明用の増分利益</span><b>${Math.round(profit).toLocaleString()}円</b><p>追加購入 ${orders.toFixed(1)}件相当 / 購入率差 ${(l-b).toFixed(1)}ポイント</p>`}else if(app==='epos-gold'){const v=['calcGold','calcMonthly','calcGoal','calcFee'].map(num);if(v.some(n=>n===null)){el.textContent='範囲内の数値を入力してください。';return}const [price,monthly,goal,fee]=v,left=Math.max(0,goal-state.goldMg/1000),points=Math.ceil(left*price),months=Math.ceil(points/monthly);el.innerHTML=`<span>現在のデモ残高 ${grams(state.goldMg)}g から</span><b>目標まで ${months}か月</b><p>必要ポイント ${points.toLocaleString()}pt / 加工・配送費 ${fee.toLocaleString()}円</p>`}}
 function feeOpinion(intent){const fee=num('calcFee');if(fee===null)return;track('fee_opinion',{fee,intent});document.getElementById('feeStatus').textContent=enabled?'この費用での意向を保存しました。':'上部の操作記録を有効にすると保存できます。'}
 function feedback(form){if(!enabled){document.getElementById('feedbackStatus').textContent='上部の「操作をこの端末に記録する」を有効にしてください。';return}track('feedback',Object.fromEntries(new FormData(form)));render();document.getElementById('feedbackStatus').textContent='回答を保存しました。下の一覧に反映しています。'}
 function download(){const quote=x=>'"'+String(x??'').replaceAll('"','""')+'"';const rows=[['app','session','event','timestamp_utc','metadata_json','source'],...recordsForApp().map(r=>[r.app,r.session,r.event,r.at,JSON.stringify(r.meta),r.source])];const blob=new Blob(['\ufeff'+rows.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=app+'_prototype_records.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function clear(){if(!confirm('この端末にある、この企画の操作記録と回答を削除しますか？'))return;records=records.filter(r=>r.app!==app);save();render()}
 function afterRender(){if(state.view==='validation'){document.getElementById('app').innerHTML=page();calculate()}const nav=document.getElementById('bottom');const b=document.createElement('button');b.textContent='検証';b.className=state.view==='validation'?'active':'';b.onclick=()=>view('validation');nav.append(b)}
 function wrap(name,after,before){const original=window[name];if(typeof original!=='function')return;window[name]=function(...args){const prev=before?.(...args);const result=original.apply(this,args);after(...args,prev);return result}}
 function install(){toolbar();wrap('render',afterRender);wrap('view',(v)=>{if(app==='epos-gold'){if(v==='convert')track('conversion_open');if(v==='reward')track('reward_open')}if(v!=='validation')track('view',{view:v})});
 if(app==='quest'){
  wrap('setTime',n=>track('recommendations',{minutes:n,events:eventsAvailable()}));
  wrap('chooseEvent',(id,camera)=>track('detour_route',{destination:state.destination,event:id,mode:camera?'camera':'map'}));
  wrap('goExit',()=>track('exit_route',{status:'出口を選択・退出未確認'}));
  wrap('advanceCamera',(delta,prev)=>{if(prev?.atEnd&&delta===1)track(prev.detour?'detour_floor':'destination_floor',{method:'manual_camera_demo',floor:'3F'})},()=>({atEnd:cameraIndex===cameraSteps.length-1,detour:state.detour}));
  document.addEventListener('change',e=>{if(e.target.id==='destination')track('journey_start',{destination:e.target.value,origin:state.origin||'アプリから直接'})});
  const qOriginal=quest;window.quest=function(){if(state.view==='insight')return page();return qOriginal()};
  wrap('render',()=>{if(state.view!=='home')return;const arrival=[...document.querySelectorAll('#app button')].find(b=>b.textContent==='到着を体験する');if(arrival)arrival.onclick=()=>{state.arrived=true;track('destination_floor',{destination:state.destination,floor:'3F',method:'manual_demo'});render();toast('目的フロアへの到着を記録しました')};if(state.detour&&state.selectedEvent){const host=document.querySelector('#app .location');if(host){const b=document.createElement('button');b.className='btn full';b.textContent='寄り道先フロアへの到着を体験';b.onclick=()=>{track('detour_floor',{event:state.selectedEvent,floor:'3F',method:'manual_demo'});toast('寄り道先フロアへの到着を記録しました')};host.after(b)}}document.querySelectorAll('.event-card').forEach((card,index)=>{const list=eventsAvailable();const id=list[index];if(!id)return;const b=document.createElement('button');b.className='btn ghost';b.textContent='詳しく見る';b.onclick=()=>{track('event_comparison',{event:id});const e=events.find(x=>x.id===id);toast(e.name+' · '+e.desc)};card.querySelector('.event-actions').prepend(b)})});
 }
 if(app==='oshii'){
  wrap('saveItem',()=>track('saved',{product:state.selected,reason:state.reason}));
  wrap('approach',(id,was)=>{if(!was&&state.notice===id){track('notice_sent',{product:id,method:'manual_proximity_demo'})}else if(was)track('notice_capped')},()=>notifiedToday());
  wrap('openNotice',()=>track('notice_open',{product:state.notice}));
  wrap('recordFit',()=>track('try_result',{product:state.selected,fit:state.saved[state.selected]?.fit}));
  wrap('order',(prev)=>{if(!prev&&state.saved[state.selected]?.ordered)track('purchase',{product:state.selected,paid:state.saved[state.selected].paid,discount:state.saved[state.selected].discount})},()=>!!state.saved[state.selected]?.ordered);
 }
 if(app==='epos-gold'){
  wrap('confirmReward',()=>{if(state.pending?.kind==='reward')track('fee_shown',{fee:3000})});
  wrap('finishAction',(action)=>{if(action&&!state.pending)track(action.kind==='points'?'converted':'redeemed',{points:action.points||0,fee:action.kind==='reward'?3000:0})},()=>state.pending?{...state.pending}:null);
 }
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&state.view!=='validation')track('screen_hidden',{view:state.view,routeOpened:!!state.detour,status:'施設退出は不明'})});
 render();
 }
 function eventsAvailable(){return app==='quest'?events.filter(e=>(state.theme==='all'||state.theme===e.theme)&&e.stay<=state.minutes).map(e=>e.id):[]}
 return {install,page,track,calculate,feedback,download,clear,feeOpinion};
})();
ConceptLab.install();
